// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crossUStatL4_c
double crossUStatL4_c(const arma::mat& X, int m);
RcppExport SEXP _usdai_crossUStatL4_c(SEXP XSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(crossUStatL4_c(X, m));
    return rcpp_result_gen;
END_RCPP
}
// crossUStatL4_cum_c
arma::vec crossUStatL4_cum_c(const arma::mat& X, int m);
RcppExport SEXP _usdai_crossUStatL4_cum_c(SEXP XSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(crossUStatL4_cum_c(X, m));
    return rcpp_result_gen;
END_RCPP
}
// crossUStatVar_cum_c
arma::mat crossUStatVar_cum_c(const arma::mat& X, int m, const arma::mat& Sigma);
RcppExport SEXP _usdai_crossUStatVar_cum_c(SEXP XSEXP, SEXP mSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(crossUStatVar_cum_c(X, m, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// crossWStatVar_c
double crossWStatVar_c(const arma::mat& X, int m, const arma::mat& Sigma);
RcppExport SEXP _usdai_crossWStatVar_c(SEXP XSEXP, SEXP mSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(crossWStatVar_c(X, m, Sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_usdai_crossUStatL4_c", (DL_FUNC) &_usdai_crossUStatL4_c, 2},
    {"_usdai_crossUStatL4_cum_c", (DL_FUNC) &_usdai_crossUStatL4_cum_c, 2},
    {"_usdai_crossUStatVar_cum_c", (DL_FUNC) &_usdai_crossUStatVar_cum_c, 3},
    {"_usdai_crossWStatVar_c", (DL_FUNC) &_usdai_crossWStatVar_c, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_usdai(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
